git:
  depth: 3

dist: bionic

os:
  - linux
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install bison flex cmake dpkg; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget 'https://launchpad.net/ubuntu/+source/bison/2:3.7+dfsg-1/+build/19640339/+files/bison_3.7+dfsg-1_amd64.deb'; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo dpkg -i ./bison_3.7+dfsg-1_amd64.deb; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install flex bison; brew link bison --force; fi

addons:
  apt:
    update: true
  homebrew:
    update: false

language: c

compiler:
  - clang
  - gcc

script:
  - ./travis/build.sh


after_success:
  # Create lcov report
  # capture coverage info
  - lcov --directory . --capture --output-file coverage.info
  # filter out system and extra files.
  # To also not include test code in coverage add them with full path to the patterns: '*/tests/*'
  - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
  # output coverage data for debugging (optional)
  - lcov --list coverage.info
  # Uploading to CodeCov
  # '-f' specifies file(s) to use and disables manual coverage gathering and file search which has already been done above
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
