git:
  depth: 3

dist: bionic

os:
  - linux
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install bison flex cmake dpkg; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget 'https://launchpad.net/ubuntu/+source/bison/2:3.7+dfsg-1/+build/19640339/+files/bison_3.7+dfsg-1_amd64.deb'; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo dpkg -i ./bison_3.7+dfsg-1_amd64.deb; fi


addons:
  apt:
    update: true
  homebrew:
    update: true
    packages:
    - bison
    - flex

language: c

compiler:
  - clang
  - gcc

script:
  - cmake .
  - cmake --build . -- -j 2
  - ctest --force-new-ctest-process --output-on-failure -j 2
